### ISSUE TITLE
Populate by Context

### ISSUE THREAD

**Issue by mike4git** [teamneusta/converter-bundle#44]
Very often some information should be directly populated as it is in the current context.
Typical examples:
- language
- locale
- user
- ...

Therefore it would be nice to offer a certain Populator doing this AND simplify its usage by extending the configuration:
```
my.converter:
    ...
    context:
        target_property: ~                        ## in case that they have the same label
        other_target_property: context_property   ## in case they are named different
```
