### ISSUE TITLE
Default value (PropertyMappingPopulator)

### ISSUE THREAD

**Issue by mike4git** [teamneusta/converter-bundle#49]
There should be a possiblity to set a default value in case of null source property value
```
...
      properties:
        - name: ~ (default: 'unknown')
```
So in case that your source object returns `null` for `$source->getName()` the target object name should be set to `'default'`.

**Comment by jan888adams** [comment]
Hi @mike4git,

I'm a bit uncertain about the best approach to resolve this ticket in a user-friendly manner. The provided example doesn't appear to be valid YAML. My suggestion is to consider two options:

    The first option is to enable setting a default value for all properties of the converter.

    The second option would allow users to map target properties to their respective default values.

The example below illustrates how this could work. In this scenario, the 'email' property would be assigned the value 'empty,' and 'firstname' would default to 'unknown.' In both cases, the source property would return null.

![image](https://github.com/teamneusta/converter-bundle/assets/56639925/850f8140-d7c5-4db7-962d-af7092ac0b84)

What are your thoughts on these ideas?"

**Comment by jdreesen** [comment]
How about defining the default values per property as follows:

```yaml
neusta_converter:
  converter:
    person.converter:
      target_factory: AppBundle\Factory\PersonFactory
      properties:
        firstname:
          default: John
        lastname: 
          source: name
          default: Doe
        email: ~
        phone: phoneNumber
      options:
        default: unknown
```

I'm also not quite convinced yet that we need a default value for all properties of a converter.
